-- MySQL Script generated by MySQL Workbench
-- Mon Aug 14 02:31:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema slade_library_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `slade_library_db` ;

-- -----------------------------------------------------
-- Schema slade_library_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `slade_library_db` DEFAULT CHARACTER SET utf8 ;
USE `slade_library_db` ;

-- -----------------------------------------------------
-- Table `slade_library_db`.`subjects`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`subjects` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`subjects` (
  `subject_id` INT NOT NULL AUTO_INCREMENT,
  `subject_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`subject_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slade_library_db`.`addresses`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`addresses` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`addresses` (
  `address_id` INT NOT NULL AUTO_INCREMENT,
  `street` VARCHAR(80) NOT NULL,
  `city` VARCHAR(40) NOT NULL,
  `postal_code` VARCHAR(10) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`address_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slade_library_db`.`members`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`members` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`members` (
  `member_id` INT NOT NULL AUTO_INCREMENT,
  `member_last_name` VARCHAR(50) NOT NULL,
  `member_first_name` VARCHAR(50) NOT NULL,
  `member_birth_date` DATE NOT NULL,
  `member_email` VARCHAR(255) NULL DEFAULT NULL,
  `enrollment_date` DATE NOT NULL,
  `address_id` INT NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`member_id`),
  INDEX `fk_members_subjects_idx` (`subject_id` ASC) VISIBLE,
  INDEX `fk_members_addresses1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_members_subjects`
    FOREIGN KEY (`subject_id`)
    REFERENCES `slade_library_db`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_members_addresses1`
    FOREIGN KEY (`address_id`)
    REFERENCES `slade_library_db`.`addresses` (`address_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slade_library_db`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`books` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`books` (
  `book_id` INT NOT NULL AUTO_INCREMENT,
  `book_title` VARCHAR(255) NOT NULL,
  `isbn` VARCHAR(30) NOT NULL,
  `subject_id` INT NOT NULL,
  PRIMARY KEY (`book_id`),
  INDEX `fk_books_subjects1_idx` (`subject_id` ASC) VISIBLE,
  CONSTRAINT `fk_books_subjects1`
    FOREIGN KEY (`subject_id`)
    REFERENCES `slade_library_db`.`subjects` (`subject_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slade_library_db`.`authors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`authors` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `author_last_name` VARCHAR(50) NOT NULL,
  `author_first_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slade_library_db`.`check_outs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`check_outs` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`check_outs` (
  `check_out_id` INT NOT NULL AUTO_INCREMENT,
  `member_id` INT NOT NULL,
  `book_id` INT NOT NULL,
  `check_out_date` DATE NOT NULL,
  `due_date` DATE NOT NULL,
  `return_date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`check_out_id`),
  INDEX `fk_check_outs_members1_idx` (`member_id` ASC) VISIBLE,
  INDEX `fk_check_outs_books1_idx` (`book_id` ASC) VISIBLE,
  CONSTRAINT `fk_check_outs_members1`
    FOREIGN KEY (`member_id`)
    REFERENCES `slade_library_db`.`members` (`member_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_check_outs_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `slade_library_db`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `slade_library_db`.`book_author`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `slade_library_db`.`book_author` ;

CREATE TABLE IF NOT EXISTS `slade_library_db`.`book_author` (
  `book_author_id` INT NOT NULL AUTO_INCREMENT,
  `book_id` INT NOT NULL,
  `author_id` INT NOT NULL,
  PRIMARY KEY (`book_author_id`),
  INDEX `fk_book_author_books1_idx` (`book_id` ASC) VISIBLE,
  INDEX `fk_book_author_authors1_idx` (`author_id` ASC) VISIBLE,
  CONSTRAINT `fk_book_author_books1`
    FOREIGN KEY (`book_id`)
    REFERENCES `slade_library_db`.`books` (`book_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_book_author_authors1`
    FOREIGN KEY (`author_id`)
    REFERENCES `slade_library_db`.`authors` (`author_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Inserts for adding test data to all tables (10 unique inserts per table)
-- -----------------------------------------------------
INSERT INTO addresses 
	(address_id, street, city, postal_code, phone_number) 
VALUES 
	(DEFAULT, '123 Elm Street', 'Oshawa', 'L1G 3J1', '(905) 555-1234'),
	(DEFAULT, '456 Maple Avenue', 'Oshawa', 'L1H 4T7', '(905) 555-5678'),
	(DEFAULT, '789 Oak Road', 'Oshawa', 'L1J 2K5', '(905) 555-9876'),
	(DEFAULT, '567 Birch Lane', 'Oshawa', 'L1K 3C9', '(905) 555-2468'),
	(DEFAULT, '890 Pine Drive', 'Oshawa', 'L1L 6P2', '(905) 555-7890'),
	(DEFAULT, '234 Cedar Street', 'Oshawa', 'L1N 5R2', '(905) 555-1357'),
	(DEFAULT, '678 Elm Crescent', 'Oshawa', 'L1M 8E7', '(905) 555-6420'),
	(DEFAULT, '345 Maple Court', 'Oshawa', 'L1W 9Z8', '(905) 555-8024'),
	(DEFAULT, '987 Oak Place', 'Oshawa', 'L1V 7T3', '(905) 555-3701'),
	(DEFAULT, '432 Birch Avenue', 'Oshawa', 'L1T 2P6', '(905) 555-9150');

INSERT INTO subjects 
	(subject_id, subject_name) 
VALUES 
	(DEFAULT, 'Gardening'),
	(DEFAULT, 'Travel'),
	(DEFAULT, 'Languages'),
	(DEFAULT, 'History'),
	(DEFAULT, 'Politics'),
	(DEFAULT, 'Horror'),
	(DEFAULT, 'Romance'),
	(DEFAULT, 'Biography'),
	(DEFAULT, 'Mythology'),
	(DEFAULT, 'Science');

INSERT INTO members 
	(member_id, member_last_name, member_first_name, member_birth_date, member_email, enrollment_date, address_id, subject_id) 
VALUES 
    (DEFAULT, 'Johnson', 'Emily', '1969-05-15', 'emily.johnson@gmail.com', '2022-03-10', 3, 8),
    (DEFAULT, 'Smith', 'Michael', '1951-09-22', 'michael.smith@hotmail.com', '2021-08-05', 7, 2),
    (DEFAULT, 'Williams', 'Olivia', '1975-12-03', 'olivia.williams@yahoo.com', '2023-01-20', 2, 5),
    (DEFAULT, 'Brown', 'Daniel', '1988-07-18', 'daniel.brown@outlook.com', '2020-11-15', 5, 4),
    (DEFAULT, 'Davis', 'Sophia', '1995-04-09', NULL, '2022-09-30', 1, 9),
    (DEFAULT, 'Martinez', 'Ethan', '1991-11-27', 'ethan.martinez@google.com', '2023-05-12', 9, 6),
    (DEFAULT, 'Anderson', 'Isabella', '1989-02-14', 'isabella.anderson@google.com', '2021-10-18', 8, 1),
    (DEFAULT, 'Hernandez', 'Liam', '2005-06-06', 'liam.hernandez@hotmail.com', '2020-07-25', 4, 1),
    (DEFAULT, 'Johnson', 'Ava', '2018-08-30', NULL, '2023-04-03', 3, 1),
    (DEFAULT, 'Wilson', 'Benjamin', '2012-01-11', 'benjamin.wilson@outlook.com', '2022-06-28', 6, 7);

INSERT INTO books 
	(book_id, book_title, isbn, subject_id) 
VALUES
	(DEFAULT, 'Gardening in North America', '978-1234567890', 1),
    (DEFAULT, 'Wanderlust Chronicles', '978-9876543210', 2),
    (DEFAULT, 'Modern Linguistics', '978-5678901234', 2),
    (DEFAULT, 'The Battles of World War II', '978-4321098765', 4),
    (DEFAULT, 'Politics Unveiled', '978-54321098760', 5),
    (DEFAULT, 'Chills in the Night', '978-6789054321', 6),
    (DEFAULT, 'Eternal Love', '978-3456789012', 7),
    (DEFAULT, 'Behind Closed Doors', '978-7890123456', 8),
    (DEFAULT, 'Greek Gods', '978-8901234567', 9),
    (DEFAULT, 'The Quantum Paradox', '978-9012345678', 10);
    
INSERT INTO authors
	(author_id, author_last_name, author_first_name)
VALUES
	(DEFAULT, 'Michaels', 'Trevor'),
	(DEFAULT, 'Bishop', 'Samual'),
	(DEFAULT, 'Lewis', 'Carol'),
	(DEFAULT, 'Green', 'David'),
	(DEFAULT, 'Rideout', 'Jackie'),
	(DEFAULT, 'Martin', 'Ellis'),
	(DEFAULT, 'Albert', 'Ivan'),
	(DEFAULT, 'Smythe', 'Lisa'),
	(DEFAULT, 'Heywood', 'Tyler'),
	(DEFAULT, 'Donnaghey', 'Steven');
    
INSERT INTO book_author
	(book_author_id, book_id, author_id)
VALUES
    (DEFAULT, 1, 2),
    (DEFAULT, 2, 2),
    (DEFAULT, 3, 3),
    (DEFAULT, 4, 4),
    (DEFAULT, 5, 5),
    (DEFAULT, 6, 7),
    (DEFAULT, 7, 7),
    (DEFAULT, 8, 8),
    (DEFAULT, 9, 9),
    (DEFAULT, 4, 5);
    
INSERT INTO check_outs
	(check_out_id, member_id, book_id, check_out_date, due_date, return_date)
VALUES
    (DEFAULT, 1, 6, '2023-07-01', DATE_ADD('2023-07-01', INTERVAL 14 DAY),'2023-07-10'),
    (DEFAULT, 2, 6, '2023-07-05', DATE_ADD('2023-07-11', INTERVAL 14 DAY),'2023-07-18'),
    (DEFAULT, 1, 3, '2023-07-10', DATE_ADD('2023-07-10', INTERVAL 14 DAY),NULL),
    (DEFAULT, 3, 7, '2023-07-12', DATE_ADD('2023-07-12', INTERVAL 14 DAY),'2023-07-25'),
    (DEFAULT, 4, 6, '2023-07-15', DATE_ADD('2023-07-20', INTERVAL 14 DAY),'2023-07-25'),
    (DEFAULT, 5, 7, '2023-07-18', DATE_ADD('2023-07-26', INTERVAL 14 DAY),NULL),
    (DEFAULT, 6, 9, '2023-07-22', DATE_ADD('2023-07-22', INTERVAL 14 DAY),'2023-07-30'),
    (DEFAULT, 7, 8, '2023-07-25', DATE_ADD('2023-07-25', INTERVAL 14 DAY),'2023-08-06'),
    (DEFAULT, 4, 6, '2023-07-28', DATE_ADD('2023-07-28', INTERVAL 14 DAY),NULL),
    (DEFAULT, 9, 2, '2023-07-30', DATE_ADD('2023-07-30', INTERVAL 14 DAY),'2023-08-16');

-- -----------------------------------------------------
-- Updating data in tables (3 unique updates per table)
-- -----------------------------------------------------
UPDATE addresses SET 
	postal_code = 'L1G 4M8'
WHERE 
	address_id = '7';
UPDATE addresses SET
	street = '965 Florell Drive'
WHERE
	address_id = '2';
UPDATE addresses SET
	phone_number = '(905) 555-1111'
WHERE
	address_id = '1';

UPDATE subjects SET
	subject_name = 'Suspense'
WHERE
	subject_id = '6';
UPDATE subjects SET
	subject_name = 'Botany'
WHERE
	subject_id = '1';
UPDATE subjects 
SET 
    subject_name = 'Modern Romance'
WHERE
    subject_id = '7';
    
UPDATE members SET
	member_email = 'sophia.davis@hotmail.com'
WHERE
	member_id = '5';
UPDATE members SET
	member_last_name = 'Roberts',
    member_email = 'isabella.roberts@gmail.com'
WHERE
	member_id = '7';
UPDATE members SET
	subject_id = '5'
WHERE
	member_id = '10';
    
UPDATE books SET
	book_title = 'Battles of World War II, The'
WHERE
	book_id = '4';
UPDATE books SET
	subject_id = '7'
  WHERE
	book_id = '2';
UPDATE books SET
	book_title = 'Politics, Behind the Veil'
WHERE
	book_id = '5';
    
UPDATE authors SET
	author_last_name = 'Rideout-Bellows'
WHERE
	author_id = '5';
UPDATE authors SET
	author_first_name = 'Lissa'
  WHERE
	author_id = '8';
UPDATE authors SET
	author_first_name = 'S.J.'
WHERE
	author_id = '2';

UPDATE check_outs SET
	check_out_date = '2023-07-12'
WHERE
	member_id = '1';
UPDATE check_outs SET
	member_id = '9'
  WHERE
	check_out_id = '2';
UPDATE check_outs SET
	check_out_date = '2023-07-20'
WHERE
	check_out_id = '5';

UPDATE book_author SET
	book_id = '4'
WHERE
	book_author_id = '5';
UPDATE book_author SET
	author_id = '9'
  WHERE
	book_author_id = '1';
UPDATE book_author SET
	author_id = '3'
WHERE
	book_author_id = '9';
    
-- -----------------------------------------------------
-- Deleting data from tables (1 unique delete per table)
-- -----------------------------------------------------
DELETE FROM addresses
WHERE
	address_id = '10';
DELETE FROM subjects
WHERE
	subject_id = '3';
DELETE FROM members
WHERE
	member_id = '8';
DELETE FROM books
WHERE
	book_id = '10';
DELETE FROM authors
WHERE
	author_id = '10';
DELETE FROM check_outs
WHERE
	check_out_id = '1';
DELETE FROM book_author
WHERE
	book_author_id = '10';
    
-- -----------------------------------------------------
-- Select statements that address the requested functionality/queries from the design specifications
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Overdue book list
-- -----------------------------------------------------
SELECT
	member_last_name AS 'Last Name',
    member_first_name AS 'First Name',
    addresses.phone_number AS 'Phone',
    book_title AS 'Book Title',
    check_outs.due_date,
    check_outs.return_date,
	CASE
		WHEN check_outs.return_date IS NOT NULL THEN 'Returned'
		WHEN check_outs.return_date IS NULL AND DATEDIFF(NOW(), check_outs.due_date) > 14 THEN 'Past due'
		ELSE 'Not due'
	END AS book_status
FROM
	addresses
		JOIN members ON addresses.address_id = members.address_id
        JOIN check_outs ON members.member_id = check_outs.member_id
        JOIN books ON check_outs.book_id = books.book_id
WHERE
	CASE
        WHEN check_outs.return_date IS NOT NULL THEN 'Returned'
        WHEN check_outs.return_date IS NULL AND DATEDIFF(NOW(), check_outs.due_date) > 14 THEN 'Past due'
        ELSE 'Not due'
    END = 'Past due';

-- -----------------------------------------------------
-- Search for book by partial title
-- -----------------------------------------------------
SELECT 
	books.book_id, 
    book_title,
	CASE
		WHEN check_out_id IS NOT NULL THEN 'Unavailable'
		ELSE 'Available'
	END AS availability
FROM 
	books
		LEFT JOIN check_outs ON books.book_id = check_outs.book_id
WHERE 
	book_title LIKE '%Chills%'
LIMIT 
	1;

-- -----------------------------------------------------
-- Show Top 10 most popular books over a date range
-- -----------------------------------------------------
SELECT
    COUNT(check_outs.book_id) AS '# Check-outs',
    book_title AS Book    
FROM
    books
		JOIN check_outs ON books.book_id = check_outs.book_id
WHERE
    check_outs.check_out_date BETWEEN '2023-07-01' AND '2023-07-30'
GROUP BY
    check_outs.book_id
ORDER BY
    COUNT(check_outs.book_id) DESC
LIMIT
	10;

-- -----------------------------------------------------
-- Most popular day of week for book check-outs
-- -----------------------------------------------------
SELECT
    DAYNAME(check_out_date) AS 'Week Day',
    COUNT(*) AS Total
FROM
    check_outs
WHERE
    check_out_date BETWEEN '2023-07-01' AND '2023-07-30'
GROUP BY
    DAYNAME(check_out_date)
ORDER BY
    Total DESC
LIMIT
    7;

-- -----------------------------------------------------
-- Most popular book categories
-- -----------------------------------------------------
SELECT
    subject_name AS Subject,
    COUNT(*) AS Checkouts
FROM
    subjects 
		JOIN books ON subjects.subject_id = books.subject_id
		JOIN check_outs ON books.book_id = check_outs.book_id
WHERE
    check_out_date BETWEEN '2023-07-01' AND '2023-07-30'
GROUP BY
    subjects.subject_id
ORDER BY
    Checkouts DESC
LIMIT
    10;
